### ISSUE TITLE
Send a message to the room, why can you receive it if you are not in this room?

### ISSUE THREAD

**Issue by einsqing** [socketio/socket.io-redis-emitter#97] opened 2021-03-28 06:32 UTC
Send a message to the room, why can you receive it if you are not in this room?

    "socket.io": "^4.0.0",
    "socket.io-client": "^4.0.0",
    "socket.io-emitter": "^3.2.0",
    "socket.io-redis": "^6.1.0",

io.to(sid).emit('hello', "to all clients in 'room42' room except sender");

**Comment by darrachequesne** [comment] 2021-05-04 06:30
Closed as duplicate of https://github.com/socketio/socket.io-redis/issues/394.

**Closed by darrachequesne** 2021-05-04 06:30 UTC
